/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sutdown_app;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import sun.audio.AudioStream;

/**
 *
 * @author Ahmed El_Sayed
 */
public class shutdownapp extends javax.swing.JFrame {

    /**
     * Creates new form shutdownapp
     */
    public shutdownapp() {
        initComponents();
        this.setLocationRelativeTo(null);
        timer.setText(String.valueOf(time));
        msg.setVisible(false);
        jButton1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        timer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Shutdown_Apps");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Shutdown Now");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, -1));

        msg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msg.setText("The Limited time is finshed! ");
        msg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, 20));

        jButton3.setText("Close");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Cancel Time");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, -1));

        jButton5.setText("Strart");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 130, -1));

        jButton4.setText("Enter Time");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        timer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timer.setText("000");
        jPanel1.add(timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 40, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("The time is :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        stil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stil.setText("000");
        jPanel1.add(stil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Stil_Min");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int time2 = Integer.parseInt(JOptionPane.showInputDialog("Enter the Time "));
        if (time2 > 0) {
            time = time2;
            timer.setText(String.valueOf(time));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please enter an intger number . dont enter char or zero number!");
        }
        jButton4.setVisible(false);
        jButton1.setVisible(false);
        msg.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (strat == -1) {
            int time2 = Integer.parseInt(JOptionPane.showInputDialog("Enter the Time "));
            if (time2 > 0) {
                time = time2;
                timer.setText(String.valueOf(time));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please enter an intger number . dont enter char or zero number!");
            }
            jButton4.setVisible(false);
            strat = 0;
            finsh = 0;
            arm();

        } else {

            finsh = 0;
            arm();
        }
        jButton1.setVisible(false);
        msg.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        finsh = 1;
        jButton1.setVisible(true);
        stil.setText("0");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        shut();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shutdownapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shutdownapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shutdownapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shutdownapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shutdownapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel stil;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables

    int time;

    public void arm() {

        Thread clok = new Thread() {
            public void run() {
                for (int i = time; i >= 0; i--) {
                    if (finsh >= 1) {
                        break;
                    }
                    stil.setText(String.valueOf(i));
                    System.out.println(i);

                    if (i == 0) {
                        msg.setVisible(true);
                        jButton1.setVisible(true);
                        shut();
                        break;
                    }
                    try {

                        sleep(6000);
                    } catch (Exception e) {

                    }

                }

            }
        };
        clok.start();

    }
    int finsh = 0;

    public void shut() {
        this.setVisible(true);
        sound();
        int reply = JOptionPane.showConfirmDialog(null, " The time is finshed,\n"
                + "Do You Want Realy Shutdown Your PC!? "
                + "plese close all running apps Befor shutdown", "Shutdown ", JOptionPane.YES_NO_OPTION);
        if (reply != JOptionPane.YES_OPTION) {

            try {
                Runtime.getRuntime().exec("shutdown -s -t 0");

            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
    }

    Clip clip;

    InputStream in;
    AudioStream audio;

    public void sound() {

        try {

            File f = new File("Logon.wav");
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(f);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Can not open the file");
        }

    }
    int strat = -1;
}
